[package]
name = "cosmwasm-ica"
authors = ["j0nl1 <jonlitech@gmail.com>"]
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.1.0", features = ["ibc3"] }
cosmwasm-schema = { version = "1.1.4" }
thiserror = { version = "1.0.37" }